name: Build and Submit Beta Track

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Setup Expo Application Services (EAS)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "shudhanshu.raj@amoga.io"
          git config --local user.name "raj-shudhanshu"

      - name: Install Dependencies
        run: npm install

      - name: Add Google Service Account Key
        run: |
          printf "%s" "${{ secrets.GOOGLE_SERVICE_KEY }}" > ./google-services.json

      - name: Push Code
        run: |
          git add . 
          git commit -m "test"
          git push origin

      - name: Build and Submit Android App
        run: |
          eas build --profile beta --platform android --non-interactive --auto-submit --no-wait --clear-cache
