name: Build and Submit Beta Track

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      
      - name: Setup Expo Application Services (EAS)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Add Google Service Account Key
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_KEY }}" | base64 --decode > ./google-services.json

      - name: Build and Submit Android App
        run: |
          eas build --profile beta --platform android --non-interactive --auto-submit --no-wait --clear-cache
